
personal-info:
  database:
    url: jdbc:mysql://localhost:3306/springdata?serverTimezone=UTC
    username: root
    password: admin
server:
  port: 8999

spring:
  jpa:
    hibernate:
      ddl-auto: update